version: '3.3'
services:
  sock-puppet-detector:
    profiles:
      - run
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:1337
  test:
    profiles:
      - test
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: python -m pytest
